# Generated by Django 3.1.1 on 2021-04-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20210409_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genresparams',
            name='viewed_genre_films',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlyparams',
            name='serials_in_month',
            field=models.PositiveIntegerField(),
        ),
    ]
